language: python

os:
    - linux
#    - osx

python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"

before_install:

install:
    - python setup.py build_ext -i

script:
    - nosetests --with-doctest triangle

notifications:
    email: false
